"""AI-03 — synthetic dataset of sprints, generated by a simulator (no real sprint history exists yet).

Each row is one sprint observed on a random day: what the backend would measure that day, and whether
the sprint ended late (story points left at the end date). The simulation:
- a team (1–8 members) with a hidden velocity per member (log-normal around 0.7 point/day) commits to
  50–125 % of what it can deliver over a 7–21-day sprint;
- blocked tasks, open high-complexity tasks and unassigned tasks slow it down ("friction");
- the past and the future velocities get random noise (log-normal, σ 0.20 and 0.25): a sprint that
  looks fine can still slip, and the other way round — the label is not a function of the features;
- the historical velocity known by the backend is the true one ± 20 %, missing for 30 % of the teams.

    python -m app.ml.sprint_risk_data      # regenerate app/ml/data/sprint_risk.csv (seed 2026)
"""

import csv
import math
import random
from pathlib import Path

from .sprint_features import SprintSnapshot

DATA_PATH = Path(__file__).parent / "data" / "sprint_risk.csv"
SEED = 2026
ROWS = 2000
COLUMNS = (
    "duration_days", "elapsed_days", "total_tasks", "done_tasks", "blocked_tasks", "high_complexity_open",
    "unassigned_open", "total_points", "done_points", "team_size", "historical_velocity", "delayed",
)


def _binomial(rng: random.Random, n: int, p: float) -> int:
    return sum(rng.random() < p for _ in range(n))


def _friction(blocked: float, high_complexity: float, unassigned: float) -> float:
    return (1 - 0.6 * blocked) * (1 - 0.25 * high_complexity) * (1 - 0.3 * unassigned)


def simulate(rng: random.Random) -> tuple[SprintSnapshot, bool]:
    duration = rng.choice((7, 10, 14, 14, 21))
    team_size = rng.randint(1, 8)
    team_velocity = rng.lognormvariate(math.log(0.7), 0.35) * team_size
    total_points = max(3, round(team_velocity * duration * rng.uniform(0.5, 1.25)))
    total_tasks = max(1, round(total_points / rng.choice((2, 3, 3, 5))))
    elapsed = round(rng.uniform(0, duration * 0.95), 1)

    blocked_rate, complex_rate, unassigned_rate = rng.betavariate(1, 8), rng.betavariate(1.5, 6), rng.betavariate(1, 6)
    past = team_velocity * _friction(blocked_rate, complex_rate, unassigned_rate) * rng.lognormvariate(0, 0.2)
    done_points = round(min(total_points, past * elapsed), 1)
    done_tasks = min(total_tasks, round(total_tasks * done_points / total_points))
    open_tasks = total_tasks - done_tasks
    blocked = _binomial(rng, open_tasks, blocked_rate)
    complex_open = _binomial(rng, open_tasks, complex_rate)
    unassigned = _binomial(rng, open_tasks, unassigned_rate)
    historical = round(team_velocity * rng.uniform(0.8, 1.2), 2) if rng.random() < 0.7 else None

    share = (lambda count: count / open_tasks) if open_tasks else (lambda count: 0.0)
    future = (
        team_velocity
        * _friction(share(blocked), share(complex_open), share(unassigned))
        * rng.lognormvariate(0, 0.25)
        * (duration - elapsed)
    )
    snapshot = SprintSnapshot(
        duration_days=duration,
        elapsed_days=elapsed,
        total_tasks=total_tasks,
        done_tasks=done_tasks,
        blocked_tasks=blocked,
        high_complexity_open=complex_open,
        unassigned_open=unassigned,
        total_points=total_points,
        done_points=done_points,
        team_size=team_size,
        historical_velocity=historical,
    )
    return snapshot, (total_points - done_points) > future


def generate(rows: int = ROWS, seed: int = SEED) -> list[tuple[SprintSnapshot, bool]]:
    rng = random.Random(seed)
    return [simulate(rng) for _ in range(rows)]


def write_dataset(path: Path = DATA_PATH) -> int:
    samples = generate()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(COLUMNS)
        for snapshot, delayed in samples:
            historical = "" if snapshot.historical_velocity is None else snapshot.historical_velocity
            writer.writerow([
                snapshot.duration_days, snapshot.elapsed_days, snapshot.total_tasks, snapshot.done_tasks,
                snapshot.blocked_tasks, snapshot.high_complexity_open, snapshot.unassigned_open,
                snapshot.total_points, snapshot.done_points, snapshot.team_size, historical, int(delayed),
            ])
    return len(samples)


def load_dataset(path: Path = DATA_PATH) -> list[tuple[SprintSnapshot, bool]]:
    with path.open(encoding="utf-8", newline="") as file:
        rows = list(csv.DictReader(file))
    return [
        (
            SprintSnapshot(
                duration_days=int(row["duration_days"]),
                elapsed_days=float(row["elapsed_days"]),
                total_tasks=int(row["total_tasks"]),
                done_tasks=int(row["done_tasks"]),
                blocked_tasks=int(row["blocked_tasks"]),
                high_complexity_open=int(row["high_complexity_open"]),
                unassigned_open=int(row["unassigned_open"]),
                total_points=int(row["total_points"]),
                done_points=float(row["done_points"]),
                team_size=int(row["team_size"]),
                historical_velocity=float(row["historical_velocity"]) if row["historical_velocity"] else None,
            ),
            row["delayed"] == "1",
        )
        for row in rows
    ]


if __name__ == "__main__":
    count = write_dataset()
    delayed = sum(label for _, label in load_dataset())
    print(f"{count} sprints written to {DATA_PATH} ({delayed} delayed, {delayed / count:.1%})")
